# -*- coding: utf-8 -*-
"""imersao_python_alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KC87DlEP1aTxpPJ8FmD9YpvdRjWNupxe

# Imersão Python Alura

## Aula 2

### Importação
"""

import pandas as pd

df_principal = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Principal")
df_principal.head(5)

df_total_acoes = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Total_de_acoes")
df_total_acoes.head(5)

df_ticker = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Ticker")
df_ticker.head(5)

df_chat_gpt = pd.read_excel("/content/acoes_aulas.xlsx", sheet_name="Chat_GPT")
df_chat_gpt.head(5)